# Use root/example as user/password credentials
version: '3.1'

services:
  main:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
    - ./:/app

  mongo:
    image: mongo:4.2.3
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      # seeding scripts
      - /mongo/init-mongo.js:/docker-entrypoint-initdb.d
      # named volumes
      - /mongo-volume:/data/db
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
